config/routes.rb
Rails.application.routes.draw do

  resources :posts, param: :slug

  resources :cities, param: :slug do
    resources :subcategories, param: :slug
    resources :categories, param: :slug 
  end 

  resources :counties, param: :slug do
    resources :subcategories, param: :slug 
    resources :categories, param: :slug 
  end

  root to: "counties#show"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  include Sluggerize
  
  has_many :subcategories
  has_many :posts

  validates_uniqueness_of :name
end

app/models/city.rb
class City < ApplicationRecord
  include Sluggerize

  belongs_to :county

  has_many :posts

  validates_uniqueness_of :name
end

app/models/concerns/sluggerize.rb
module Sluggerize
  extend ActiveSupport::Concern

  included do
    before_save :generate_slug_from_slug_field
    validates_uniqueness_of :slug

    def generate_slug_from_slug_field
      self.slug = Slug.new(self).generate
    end

    def to_param
      slug
    end

    def slug_field
      try(:name) || raise("Name does not exist! Please set slug field.")
    end
  end
end

app/models/county.rb
class County < ApplicationRecord
  include Sluggerize

  has_many :cities
  has_many :posts

  validates_uniqueness_of :name
end

app/models/post.rb
class Post < ApplicationRecord
  include Sluggerize

  belongs_to :county, optional: true
  belongs_to :city, optional: true
  belongs_to :category, optional: true
  belongs_to :subcategory, optional: true

  has_many_attached :photos

  validates_uniqueness_of :title

  scope :per_subcategory, -> (subcategory) { where(subcategory_id: subcategory.id) }
  scope :per_category, -> (category) { where(category_id: category.id) }
  scope :filter_by, -> (title) { where("title ilike ?", title) }
  scope :filter_price_max, -> (max) { where("price_cents <= ?", max) }
  scope :filter_price_min, -> (min) { where("price_cents >= ?", min) }

  def slug_field
    title
  end
end

app/models/slug.rb
class Slug
  def initialize(object)
    @object = object
  end

  def generate
    "#{candidate}#{suffix}"
  end

  private
  def candidate
    @object.slug_field.parameterize
  end
  
  def suffix
    duplicate?? "-#{Time.now.to_s.parameterize}" : nil
  end

  def duplicate?
    @object.class.find_by(slug: candidate).present?
  end
end

app/models/subcategory.rb
class Subcategory < ApplicationRecord
  include Sluggerize

  belongs_to :category

  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/base_controller.rb
class BaseController < ApplicationController

  def index
  end

  def category
  end

  def item
  end

  def new_post
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  include Pagy::Backend
  include Locationize

  def show
    @category = Category.find_by(slug: params[:slug])
    title = "%#{params[:title]}%"
    price_min = params[:price_min]
    price_max = params[:price_max]
    @posts = location.posts.per_category(@category).filter_by(title)
    @posts = @posts.filter_price_min(price_min) if price_min.present?
    @posts = @posts.filter_price_max(price_max) if price_max.present?
    @posts = @posts.order(:price_cents)
    @pagy, @posts = pagy(@posts, items: 12)
  end

end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController

  def show
    @city = City.find_by(slug: params[:slug])
    @county = @city.county
  end

end

app/controllers/concerns/locationalize.rb
module Locationalize
  extend ActiveSupport::Concern

  included do
    before_action :set_location

    def set_location
      @city = City.find_by(slug: params[:city_slug])
      @county = @city.try(:county) || County.find_by(slug: params[:county_slug])
    end
  end

end

app/controllers/concerns/locationize.rb
module Locationize
  extend ActiveSupport::Concern

  included do
    before_action :set_location

    def set_location
      @city = City.find_by(slug: params[:city_slug])
      @county = @city.try(:county) || County.find_by(slug: params[:county_slug])
    end

    def location
      @city || @county
    end
  end

end

app/controllers/counties_controller.rb
class CountiesController < ApplicationController

  def show 
    @county = County.find_by(slug: params[:slug]) || County.first
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def new
    @tabs= %w{county city category subcategory content map photos preview}
    @post = Post.new
    @county = County.first
  end

  def show
    @post = Post.find_by(slug: params[:slug])
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to root_path, notice: "Post successfully created."
    else
      render :new
    end
  end

  private
  def post_params
    params.require(:post).permit(:county_id, :city_id, :category_id, :subcategory_id, :slug, :state, :email, :phone, :description, :title, :zip, :price_cents, :city_or_province, :street_address, :photos => [] )
  end

end

app/controllers/subcategories_controller.rb
class SubcategoriesController < ApplicationController
  include Locationize
  include Pagy::Backend

  def show
    @subcategory = Subcategory.find_by(slug: params[:slug])
    @category = @subcategory.category
    @posts = location.posts.per_subcategory(@subcategory)
    title = "%#{params[:title]}%"
    price_min = params[:price_min]
    price_max = params[:price_max]
    @posts = @posts.filter_by(title)
    @posts = @posts.filter_price_min(price_min) if price_min.present?
    @posts = @posts.filter_price_max(price_max) if price_max.present?
    @posts = @posts.order(:price_cents)
    @pagy, @posts = pagy(@posts, items: 12)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/cities_helper.rb
module CitiesHelper

  def active_city(city)
    city == @city ? 'active strong' : 'small'
  end

end

app/helpers/counties_helper.rb
module CountiesHelper
end

app/helpers/subcategories_helper.rb
module SubcategoriesHelper
end

app/views/application/_brand.html.erb
<h1 class="display-4 text-center mb-2">
  samslist
</h1>

app/views/application/_card.html.erb
<div class="card mb-4">
  <%= image_tag post.photos.first, class: "card-img-top", style: "height:250px; object-fit:cover" %>
  <div class="card-body">
    <h3 class="card-title text-truncate"><%= post.title %></h3>
    <h5 class="card-subtitle mb-3">$<%= post.price_cents%></h5>
    <p class="card-text text-truncate"><%= post.description %></p>
  </div>
  <div class="card-footer">
    <%= post.city_or_province %>, <%= post.state %>
  </div>
  <div class="card-footer">
    <%= link_to "See Item", post_path(post), class: "card-link" %>
  </div>
</div>

app/views/application/_cities.html.erb
<div class="list-group mb-2">
  <a href="#" class="list-group-item list-group-item-action bg-light">
    Cities
  </a>

  <% @cities = City.all %>

  <% @cities.each do |city| %>
    <%= link_to city.name, city, :class => "list-group-item text-muted list-group-item-action text-truncate" %>
  <% end %>
</div>

app/views/application/_city_listings.html.erb
<%= link_to category.name, city_category_path(@city, category), :class => "list-group-item list-group-item-action bg-light text-truncate" %>

<% category.subcategories.each do |subcategory| %>
  <%= link_to subcategory.name, city_subcategory_path(@city, subcategory), :class => "list-group-item list-group-item-action text-truncate" %>
<% end %>
<br>

app/views/application/_cta.html.erb
<div class="mt-2">
  <%= link_to "Create a Post", "/posts/new", :class => "btn btn-primary btn-block" %>
</div>

<div class="mt-2">
  <button type="button" class="btn btn-info btn-block">My Account</button>
</div>

<form class="mt-2">
    <div class="form-group">
      <input class="form-control" type="text" placeholder="search samslist">
    </div>
</form>

app/views/application/_filter-tools.html.erb
<form class="needs-validation" novalidate>

  <!-- title -->
  <div class="form-row">
    <div class="col-md-12 mb-3">
      <label>Search By Title</label>
      <input name="title" method="get" type="text" class="form-control" 
      placeholder="Title of Listing" value="<%= params[:title] %>">
    </div>
  </div>

  <!-- price -->
  <p class="mb-2">Filter By Price</p>
  <div class="form-row">
		<div class="col-6 mb-3">
      <div class="input-group">
        <div class="input-group-prepend">
          <span class="input-group-text" id="inputGroupPrepend">$</span>
        </div>
        <input name="price_min" method="get" type="text" class="form-control" placeholder="Min" value="<%= params[:price_min] %>" aria-describedby="inputGroupPrepend">
      </div>
    </div>
		<div class="col-6 mb-3">
      <div class="input-group">
        <div class="input-group-prepend">
          <span class="input-group-text" id="inputGroupPrepend">$</span>
        </div>
        <input name="price_max" method="get" type="text" class="form-control" placeholder="Max" value="<%= params[:price_max] %>" aria-describedby="inputGroupPrepend">
      </div>
    </div>

  </div>

  <!--
	<div class="custom-control custom-checkbox">
		<input type="checkbox" class="custom-control-input" id="customCheck1">
		<label class="custom-control-label" for="customCheck1">Check this custom checkbox</label>
	</div>

	<div class="custom-control custom-radio">
		<input type="radio" id="customRadio1" name="customRadio" class="custom-control-input">
		<label class="custom-control-label" for="customRadio1">Toggle this custom radio</label>
	</div>
	<div class="custom-control custom-radio">
		<input type="radio" id="customRadio2" name="customRadio" class="custom-control-input">
		<label class="custom-control-label" for="customRadio2">Or toggle this other custom radio</label>
	</div>

	<div class="custom-control custom-switch">
		<input type="checkbox" class="custom-control-input" id="customSwitch1">
		<label class="custom-control-label" for="customSwitch1">Toggle this switch element</label>
	</div>
	<div class="custom-control custom-switch">
		<input type="checkbox" class="custom-control-input" disabled id="customSwitch2">
		<label class="custom-control-label" for="customSwitch2">Disabled switch element</label>
	</div>

	<select class="custom-select mb-3 mt-3">
		<option selected>Open this select menu</option>
		<option value="1">One</option>
		<option value="2">Two</option>
		<option value="3">Three</option>
	</select>

	<label for="customRange1">Example range</label>
	<input type="range" class="custom-range" id="customRange1">
  -->

  <!-- submit button -->
  <button class="btn btn-primary mt-3 mb-3" type="submit">Submit form</button>

</form>

<script>
// Example starter JavaScript for disabling form submissions if there are invalid fields
(function() {
  'use strict';
  window.addEventListener('load', function() {
    // Fetch all the forms we want to apply custom Bootstrap validation styles to
    var forms = document.getElementsByClassName('needs-validation');
    // Loop over them and prevent submission
    var validation = Array.prototype.filter.call(forms, function(form) {
      form.addEventListener('submit', function(event) {
        if (form.checkValidity() === false) {
          event.preventDefault();
          event.stopPropagation();
        }
        form.classList.add('was-validated');
      }, false);
    });
  }, false);
})();
</script>

app/views/application/_footer.html.erb
<footer class="container-fluid bg-light mt-3 p-3">
  <ul class="nav justify-content-center"> 
  <li class="nav-item">
    <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">© samslist</a>
  </li>
  <li class="nav-item">
    <a class="nav-link active" href="#">Active</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="#">Link</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="#">Link</a>
  </li>
  <li class="nav-item">
    <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
  </li>
  </ul>
</footer>

app/views/application/_list.html.erb
<%= link_to category.name, county_category_path(@county, category), :class => "list-group-item list-group-item-action bg-light text-truncate" %>

<% category.subcategories.each do |subcategory| %>
  <%= link_to subcategory.name, county_subcategory_path(@county, subcategory), :class => "list-group-item list-group-item-action text-truncate" %>
<% end %>
<br>

app/views/application/_metadata.html.erb
<nav class="nav">
  <a class="nav-link active" href="#">My Info</a>
  <a class="nav-link" href="#">Link</a>
  <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
  <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
</nav>

app/views/application/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light mb-3">

<%= link_to @county.name, @county, :class => "navbar-brand" %>

<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>

<div class="collapse navbar-collapse" id="navbarNav">

  <ul class="navbar-nav">
    <% @county.cities.each do |city| %>
      <li>
        <%= link_to city.name, city, :class => "nav-link #{active_city(city)}" %>
      </li>
    <% end %>
  </ul>

</div>

</nav>

app/views/application/_pagination.html.erb
<div class="mb-4 mt-3">
  <div class="lead mb-2">
    <%== pagy_info(@pagy) %>
  </div>
  <%== pagy_bootstrap_nav(@pagy) %>
</div>

app/views/categories/show.html.erb
<div class="container-fluid">

  <div class="row mt-md-3 mt-lg-4">
    <div class="col">
      <%= render "navbar" %>
    </div>
  </div>

  <div class="row">

    <!-- 1st column -->
    <div class="col-md-3 small">
      <%= render "brand" %>
      <h2 class="display-5 mb-4 text-secondary text-center"><%= @category.name %></h2>
      <%= render "filter-tools" %>
    </div>

    <!-- 2nd column -->
    <div class="col-md-9 small">
      <%= render "pagination" %>

      <div class="card-deck">
        <% @posts.each do |post| %>
            <div class="col-lg-4 col-sm-6">
              <%= render "card", post: post %>
            </div>
        <% end %>
      </div>

    </div>

  </div>
</div>

  

app/views/cities/show.html.erb
<div class="container-fluid">

  <div class="row mt-md-3 mt-lg-4">
    <div class="col offset-md-3">
      <%= render "navbar" %>
    </div>
    <div class="col-md-2"></div>
  </div>

  <div class="row">

    <!-- 1st column -->
    <div class="col-md-3">
      <%= render "brand" %>
      <%= render "cta" %>
    </div>

    <!-- 2nd column -->
    <div class="col-md-7 small">

      <div class="row">
          <% categories = Category.all.to_a %>
          <div class="col-4">
            <% categories[0..2].each do |category| %>
              <%= render "city_listings", category: category %>
            <% end %>
          </div>
          <div class="col-4">
            <%= render "city_listings", category: categories[3] %>
          </div>
          <div class="col-4">
            <% categories[4..5].each do |category| %>
              <%= render "city_listings", category: category %>
            <% end %>
          </div>
      </div>

    </div>

    <!-- 3rd column -->
    <div class="col-md-2 col-sm-12 small">
      <%= render "cities" %>
    </div>

  </div>
</div>

  

app/views/counties/show.html.erb
<div class="container-fluid">
  <div class="alert alert-success alert-dismissible fade <%= :show if notice %>" role="alert">
  <%= notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

  <div class="row mt-md-3 mt-lg-4">
    <div class="col offset-md-3">
      <%= render "navbar" %>
    </div>
    <div class="col-md-2"></div>
  </div>

  <div class="row">

    <!-- 1st column -->
    <div class="col col-md-3">
      <%= render "brand" %>
      <%= render "cta" %>
    </div>

    <!-- 2nd column -->
    <div class="col-md-7 small">
      <div class="row">
        <% categories = Category.all.to_a %>
        <div class="col-12 col-lg-4">
          <% categories[0..2].each do |category| %>
            <%= render "list", category: category %>
          <% end %>
        </div>

        <div class="col-12 col-lg-4">
          <%= render "list", category: categories[3] %>
        </div>

        <div class="col-12 col-lg-4">
          <% categories[4..5].each do |category| %>
            <%= render "list", category: category %>
          <% end %>
        </div>
      </div>
    </div>

    <!-- 3rd column -->
    <div class="col-md-2 col-sm-12 small">
      <%= render "cities" %>
    </div>

  </div>
</div>

  

app/views/posts/_breadcrumb.html.erb
<nav class="navbar navbar-light bg-light mb-4 p-4">

  <ol class="nav">
    <li class="breadcrumb-item">
      <%= link_to @post.county.name, county_path(@post.county) %>
    </li>
    <li class="breadcrumb-item">
      <%= link_to @post.city.name, city_path(@post.city) %>
    </li>
    <li class="breadcrumb-item">
      <%= link_to @post.category.name, county_category_path(@post.county, @post.category) %>
    </li>
    <li class="breadcrumb-item">
      <%= link_to @post.subcategory.name, county_subcategory_path(@post.county, @post.subcategory) %>
    </li>
    <li class="breadcrumb-item active" aria-current="page"><%= @post.title %></li>
  </ol>

  <ul class="nav justify-content-end">
    <li class="nav-item">
      <%= link_to "Create a Post", new_post_path, class: "nav-link" %>
    </li>
    <li class="nav-item">
      <div class="nav-link disabled">|</div>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">Link</a>
    </li>
  </ul>

</nav>

app/views/posts/_carousel.html.erb
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <% photos.each.with_index do |photo, index| %>
      <li data-target="#carouselExampleIndicators" data-slide-to="<%= index %>" class="<%= :active if index==0 %>"></li>
    <% end %>
  </ol>
 
  <div class="carousel-inner">
    <% photos.each.with_index do |photo, index| %>
      <div class="carousel-item <%= :active if index==0 %>">
        <%= image_tag photo, class: "w-100 d-block" %>
      </div>
    <% end %>
  </div> 

  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<div class="row">
  <div class="col mt-2">
    <div class="btn-group">
      <% @post.photos.each.with_index do |photo, index| %>
        <button type="button" class="btn btn-light p-0" data-carousel-target-id="<%= index %>">
          <%= image_tag photo, class: "w-100" %>
        </button>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/_city.html.erb
<h1 class="display-4 text-center mb-4">Choose your city:</h1>

<div class="col offset-lg-4">
  <% City.all.each do |city| %>
    <div class="form-check mb-2">
      <%= radio_button(:post, :city_id, city.id, class: "form-check-input") %>
      <label class="form-check-label" for="exampleRadios1">
        <%= city.name %>
      </label>
    </div>
  <% end %>

</div>

<div class="row text-center">
  <div class="col">
    <a class="btn btn-outline-primary btn-lg" href="#prev">
      Prev
    </a>
  </div>
  <div class="col">
    <a class="btn btn-outline-primary btn-lg" href="#next">
      Next
    </a>
  </div>
</div>

app/views/posts/_content.html.erb
<h1 class="display-4 text-center mb-4">Edit Your Post:</h1>
<form>

  <!-- title -->
  <div class="form-group col-md-6 offset-lg-3">
    <label for="formGroupExampleInput">Title of your post</label>
    <%= form.text_field :title, class: "form-control", placeholder: "Title" %>
  </div>

  <!-- price -->
  <div class="form-group col-md-6 offset-lg-3">
    <label for="formGroupExampleInput">Price</label>
    <div class="input-group mb-2">
      <div class="input-group-prepend">
        <div class="input-group-text">$</div>
      </div>
      <%= form.text_field :price_cents, class: "form-control", placeholder: "Amount" %>
    </div>
  </div>

  <!-- phone -->
  <div class="form-group col-md-6 offset-lg-3">
    <label for="inputPhone">Phone Number</label>
    <%= form.text_field :phone, class: "form-control" %>
  </div>

  <!-- email -->
  <div class="form-group col-md-6 offset-lg-3">
    <label for="inputEmail">Email</label>
    <%= form.text_field :email, class: "form-control" %>
  </div>

  <!-- address -->
  <div class="form-group col-md-6 offset-lg-3">
    <label for="inputAddress">Address</label>
    <%= form.text_field :street_address, class: "form-control", placeholder: "1234 Main St" %>
  </div>

  <!-- city/province -->
  <div class="form-group col-md-6 offset-lg-3">
    <label for="inputCity">City Or Province</label>
    <%= form.text_field :city_or_province, class: "form-control" %>
  </div>

  <!-- state -->
  <div class="form-row ml-2">
    <div class="form-group col-md-3 offset-lg-3">
      <label for="inputState">State</label>
      <%= form.text_field :state, class:"form-control" %>
      <!--
      <select id="inputState" class="form-control">
        <option selected>Choose...</option>
        <option>California</option>
      </select>
      -->
    </div>
    <!-- zip -->
    <div class="form-group col-md-2">
      <label for="inputZip">Zip</label>
      <%= form.text_field :zip, class: "form-control" %>
    </div>
  </div>

  <!-- description -->
  <div class="form-group col-md-6 offset-lg-3">
    <label for="exampleFormControlTextarea1">Description</label>
    <%= form.text_area :description, class: "form-control" %>
  </div>
</form>

<div class="row text-center">
  <div class="col">
    <a class="btn btn-outline-primary btn-lg" href="#prev">
      Prev
    </a>
  </div>
  <div class="col">
    <a class="btn btn-outline-primary btn-lg" href="#next">
      Next
    </a>
  </div>
</div>

app/views/posts/_continue-button.html.erb
<div class="row mt-3 mb-4">
	<div class="col offset-8">
  <a href="/post/new/<%= step %>" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Continue</a>
	</div>
</div>

app/views/posts/_county.html.erb
<h1 class="display-4 text-center mb-4">Choose your county:</h1>

<div class="col offset-lg-4">
  <% County.all.each do |county| %>
      <div class="form-check mb-2">
        <%= radio_button(:post, :county_id, county.id, class: "form-check-input") %>
        <label class="form-check-label" for="exampleRadios1">
          <%= county.name %>
        </label> 
      </div>
  <% end %>
</div>

<div class="row text-center">
  <div class="col">
    <a class="btn btn-outline-primary btn-lg" href="#prev">
      Prev
    </a>
  </div>
  <div class="col">
    <a class="btn btn-outline-primary btn-lg" href="#next">
      Next
    </a>
  </div>
</div>

app/views/posts/_map.html.erb
<h1 class="display-4 mb-4 text-center">Find Your Location:</h1>
<div class="text-center">
	<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3166.6115286180047!2d-121.91818468519044!3d37.46989307981604!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x808fc61c89f7dbf5%3A0xadd4d6fec767fe17!2s48482%20Arkansas%20Pl%2C%20Fremont%2C%20CA%2094539!5e0!3m2!1sen!2sus!4v1568831985578!5m2!1sen!2sus" width="800" height="600" frameborder="0" style="border:0;" allowfullscreen=""></iframe>
</div>

<div class="row text-center">
  <div class="col">
    <a class="btn btn-outline-primary btn-lg" href="#prev">
      Prev
    </a>
  </div>
  <div class="col">
    <a class="btn btn-outline-primary btn-lg" href="#next">
      Next
    </a>
  </div>
</div>

app/views/posts/_preview.html.erb
<h1 class="display-4 text-center">Preview</h1>

<div class="row mt-3 mb-4">
	<div class="col text-center">
  <%= form.submit("Submit", class: "btn btn-success btn-lg") %>
	</div>
</div>

<div class="row text-center">
  <div class="col">
    <a class="btn btn-outline-primary btn-lg" href="#prev">
      Prev
    </a>
  </div>
  <div class="col">
    <a class="btn btn-outline-primary btn-lg" href="#next">
      Next
    </a>
  </div>
</div>

app/views/posts/_subcategory.html.erb
<h1 class="display-4 text-center mb-4">Choose the subcategory:</h1>

<div class="col offset-lg-4">
  <% Subcategory.all.each do |subcategory| %>
    <div class="form-check mb-2">
      <%= form.radio_button :subcategory_id, subcategory.id, class: "form-check-input" %>
      <label class="form-check-label" for="exampleRadios1">
        <%= subcategory.name %>
      </label>
    </div>
  <% end %>

</div>

<div class="row text-center">
  <div class="col">
    <a class="btn btn-outline-primary btn-lg" href="#prev">
      Prev
    </a>
  </div>
  <div class="col">
    <a class="btn btn-outline-primary btn-lg" href="#next">
      Next
    </a>
  </div>
</div>

app/views/posts/_type.html.erb
<h1 class="display-4 text-center mb-4">Choose the type of post:</h1>

<div class="col offset-lg-4">
  <% Category.all.each do |category| %>
    <div class="form-check mb-2">
      <input class="form-check-input" type="radio" name="exampleRadios" id="exampleRadios1" value="option1" checked>
      <label class="form-check-label" for="exampleRadios1">
        <%= category.name %>
      </label>
    </div>
  <% end %>

</div>

<div class="col">
  <%= render "/post/continue-button", step: "category" %>
</div>

app/views/posts/new.html.erb
<div class="container-fluid">

  <div class="row mt-md-3 mt-lg-4">
    <div class="col">
      <nav class="navbar navbar-light bg-light mb-4 p-4">
        <ol class="nav">
          <li class="breadcrumb-item">
            <%= link_to "< Back", :back %>
          </li>
        </ol>

        <ul class="nav justify-content-end">
          <li class="nav-item">
            <%= link_to "Create a Post", new_post_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <div class="nav-link disabled">|</div>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
        </ul>
      </nav>
    </div>
  </div>

  <ul class="nav nav-pills mb-3 justify-content-center" id="pills-tab" role="tablist">
    <% @tabs.each.with_index do |tab, index| %>
      <li class="nav-item">
        <a class="nav-link <%= :active if index==0 %>" 
        id="pills-<%= tab %>-tab" data-toggle="pill" href="#pills-<%= tab %>" role="tab" aria-controls="pills-<%= tab %>" aria-selected="false">
          <%= tab.capitalize %>
        </a>
      </li>
    <% end %>
  </ul>

  <%= form_for @post do |form| %>
    <div class="tab-content" id="pills-tabContent">
      <% @tabs.each.with_index do |tab, index| %>
        <div class="tab-pane fade show <%= :active if index==0 %>" href="#pills-<%= tab %>" id="pills-<%= tab %>" role="tabpanel" aria-labelledby="pills-<%= tab %>-tab">
          <%= render tab, form: form %>
        </div>
      <% end %>
    </div>
  <% end %>

</div>

app/views/posts/photos.html.erb
<img src="..." alt="..." class="img-thumbnail rounded">